
// This file is auto-generated by generateApiHooks.js. Do not edit manually.
// To regenerate, run 'npm run gen:api:client' or 'npm run dev'.
import { useQuery, useMutation } from '@tanstack/react-query';

// --- API Client Configuration ---
// Import from centralized config
import { API_BASE_URL } from '../config/api';

/**
 * A generic API client that handles different content types.
 * @param {string} method HTTP method (e.g., 'get', 'post')
 * @param {string} path API endpoint path
 * @param {any} data Request body data
 * @param {string} contentType The Content-Type header value
 */
async function apiClient(method, path, data = null, contentType = 'application/json') {
  const url = `${API_BASE_URL}${path}`;
  const options = {
    method: method.toUpperCase(),
  };

  // Add authorization header if token exists
  const token = localStorage.getItem('accessToken');
  if (token) {
    options.headers = {
      'Authorization': `Bearer ${token}`,
    };
    console.log('API call with token:', token.substring(0, 10) + '...');
  } else {
    console.log('No token found for API call to:', path);
  }

  if (data) {
    if (contentType === 'multipart/form-data') {
      options.body = data; // Assumes data is already a FormData object
    } else {
      options.headers = {
        ...options.headers,
        'Content-Type': contentType,
      };
      options.body = JSON.stringify(data);
    }
  }

  const response = await fetch(url, options);

  if (!response.ok) {
    const error = new Error(`API request failed with status ${response.status}`);
    try {
      error.response = await response.json();
    } catch (e) {
      error.response = await response.text();
    }
    throw error;
  }

  if (response.headers.get('content-type')?.includes('application/json')) {
    return response.json();
  }
  
  return response.text();
}

// --- Generated Models & Types ---
/**
 * @typedef {object} AnalysisStatus
 */
/**
 * @typedef {object} Body_parse_resume_builder_api_v1_resumes_builder_parse_post
 * @property {string} file
 */
/**
 * @typedef {object} Body_upload_resume_api_v1_resumes_post
 * @property {string} file
 * @property {object} callback_url
 */
/**
 * @typedef {object} CertificationSchema
 * @property {object} name
 * @property {object} issuer
 * @property {object} date
 * @property {object} url
 */
/**
 * @typedef {object} EducationSchema
 * @property {object} institution
 * @property {object} degree
 * @property {object} field
 * @property {object} start_date
 * @property {object} end_date
 * @property {object} gpa
 */
/**
 * @typedef {object} ExperienceSchema
 * @property {object} company
 * @property {object} position
 * @property {object} start_date
 * @property {object} end_date
 * @property {object} description
 * @property {string[]} achievements
 */
/**
 * @typedef {object} ExportRequestSchema
 * @property {ResumeDataSchema} data
 */
/**
 * @typedef {object} HTTPValidationError
 * @property {ValidationError[]} detail
 */
/**
 * @typedef {object} HealthModel
 * @property {string} status
 * @property {string} service
 * @property {string} version
 * @property {string} timestamp
 */
/**
 * @typedef {object} HealthZModel
 * @property {string} status
 */
/**
 * @typedef {object} PersonalInfoSchema
 * @property {object} name
 * @property {object} email
 * @property {object} phone
 * @property {object} location
 * @property {object} linkedin
 * @property {object} github
 * @property {object} website
 */
/**
 * @typedef {object} ProjectSchema
 * @property {object} name
 * @property {object} description
 * @property {string[]} technologies
 * @property {object} url
 */
/**
 * @typedef {object} ResumeAnalysis
 * @property {integer} id
 * @property {AnalysisStatus} status
 * @property {string[]} skills
 * @property {object} extracted_text
 * @property {object} ai_model
 * @property {object} error_message
 */
/**
 * @typedef {object} ResumeDataSchema
 * @property {object} template
 * @property {PersonalInfoSchema} personal_info
 * @property {object} summary
 * @property {string[]} skills
 * @property {ExperienceSchema[]} experience
 * @property {EducationSchema[]} education
 * @property {ProjectSchema[]} projects
 * @property {CertificationSchema[]} certifications
 * @property {string[]} hobbies
 */
/**
 * @typedef {object} ResumeGenerateRequestSchema
 * @property {ResumeDataSchema} data
 * @property {object} job_description
 */
/**
 * @typedef {object} ResumeGenerateResponseSchema
 * @property {boolean} success
 * @property {string} generated_resume
 */
/**
 * @typedef {object} ResumeParseResponseSchema
 * @property {boolean} success
 * @property {ResumeDataSchema} data
 * @property {string} extracted_text
 */
/**
 * @typedef {object} ResumeRead
 * @property {object} filename
 * @property {object} callback_url
 * @property {integer} id
 * @property {object} content_type
 * @property {object} file_url
 * @property {AnalysisStatus} status
 * @property {object} ai_model
 * @property {string} created_at
 * @property {string} updated_at
 */
/**
 * @typedef {object} RootModel
 * @property {string} message
 * @property {string} version
 * @property {string} docs
 * @property {string} health
 */
/**
 * @typedef {object} ValidationError
 * @property {object[]} loc
 * @property {string} msg
 * @property {string} type
 */
/**
 * @typedef {object} BehavioralEvaluationRequest
 * @property {string} question
 * @property {string} response
 */
/**
 * @typedef {object} BehavioralEvaluationResult
 * @property {string} evaluation
 */
/**
 * @typedef {object} BehavioralRequest
 * @property {string} skills
 * @property {string} level
 * @property {string} job_role
 * @property {string} test_type
 * @property {string} company
 */
/**
 * @typedef {object} ChallengeRequest
 * @property {string} skills
 * @property {string} job_role
 * @property {string} job_description
 * @property {string} level
 * @property {string} company
 */
/**
 * @typedef {object} ChallengeResponse
 * @property {string} challenge
 */
/**
 * @typedef {object} CodeEvaluationRequest
 * @property {string} challenge
 * @property {string} solution
 */
/**
 * @typedef {object} CodeEvaluationResponse
 * @property {string} evaluation
 */
/**
 * @typedef {object} CodingProfile
 * @property {string} Education
 * @property {integer} Years_of_Experience
 * @property {integer} Project_Count
 * @property {string} Domain
 * @property {object} Skills
 * @property {string} Certifications
 * @property {string} Skill_Level
 */
/**
 * @typedef {object} CodingQuestionResult
 * @property {string} question
 * @property {number} reward
 * @property {string[]} rationale
 */
/**
 * @typedef {object} CodingQuestionsResponse
 * @property {object} profile_used
 * @property {CodingQuestionResult[]} generated_questions
 * @property {number} total_latency_sec
 */
/**
 * @typedef {object} CompanyAnswerEvaluationResponse
 * @property {string} evaluation
 */
/**
 * @typedef {object} CompanyAnswerRequest
 * @property {string} company
 * @property {string} round
 * @property {string} question
 * @property {string} answer
 * @property {string} type
 * @property {string} role
 * @property {string} experience
 */
/**
 * @typedef {object} CompanyQuestionRequest
 * @property {string} company
 * @property {string} round
 * @property {string} focus
 * @property {string} description
 * @property {string} type
 * @property {string} role
 * @property {string} experience
 */
/**
 * @typedef {object} CompanyQuestionResponse
 * @property {string} question
 */
/**
 * @typedef {object} CoursesResources
 * @property {string[]} online_courses
 * @property {string[]} tutorials_guides
 * @property {string[]} books
 * @property {string[]} workshops_conferences
 * @property {string[]} communities_forums
 */
/**
 * @typedef {object} EvaluateByIdsRequest
 * @property {integer[]} question_ids
 * @property {string[]} selected_options
 */
/**
 * @typedef {object} EvaluateResponse
 * @property {integer} score
 * @property {integer} total
 * @property {boolean} passed
 * @property {number} time_taken
 * @property {EvaluationResult[]} results
 */
/**
 * @typedef {object} EvaluationResult
 * @property {string} question
 * @property {string} user_answer
 * @property {string} correct_answer
 * @property {boolean} is_correct
 */
/**
 * @typedef {object} GenerateResponse
 * @property {integer} seed
 * @property {PublicMCQ[]} questions
 */
/**
 * @typedef {object} InterviewPDFRequest
 * @property {number} final_score
 * @property {object} scores
 * @property {object} section_times
 * @property {object} recommendations
 * @property {string} skills
 * @property {string} test_type
 */
/**
 * @typedef {object} InterviewPDFResponse
 * @property {string} assessment
 */
/**
 * @typedef {object} MCQOption
 * @property {string} label
 * @property {string} text
 */
/**
 * @typedef {object} MCQQuestion
 * @property {integer} id
 * @property {string} text
 * @property {MCQOption[]} options
 * @property {string} correct_label
 */
/**
 * @typedef {object} MCQRequest
 * @property {string} skills
 * @property {string} level
 * @property {string} job_role
 * @property {string} job_description
 * @property {string} test_type
 */
/**
 * @typedef {object} MCQResponse
 * @property {MCQQuestion[]} questions
 */
/**
 * @typedef {object} PerformanceGapsLearningResources
 * @property {string[]} online_courses
 * @property {string[]} books_articles
 * @property {string[]} workshops_conferences
 * @property {string[]} communities_forums
 */
/**
 * @typedef {object} PerformanceGapsPriorityItem
 * @property {string} name
 * @property {string} priority
 */
/**
 * @typedef {object} PerformanceGapsRequest
 * @property {object} scores
 * @property {string} feedback
 */
/**
 * @typedef {object} PerformanceGapsResponse
 * @property {string[]} strengths
 * @property {string[]} areas_for_improvement
 * @property {object} action_items
 * @property {PerformanceGapsLearningResources} learning_resources
 * @property {Timeline} timeline
 * @property {PerformanceGapsPriorityItem[]} priority_ranking
 */
/**
 * @typedef {object} PublicMCQ
 * @property {integer} id
 * @property {string} question
 * @property {string[]} options
 * @property {string} topic
 * @property {string} difficulty
 */
/**
 * @typedef {object} ReportRequest
 * @property {object[]} jobs
 * @property {object} analysis
 */
/**
 * @typedef {object} ReportResponse
 * @property {object} report
 */
/**
 * @typedef {object} SkillRecommendationsRequest
 * @property {string} skills
 * @property {object} scores
 */
/**
 * @typedef {object} SkillRecommendationsResponse
 * @property {string} assessment_summary
 * @property {string[]} learning_paths
 * @property {CoursesResources} courses_resources
 * @property {string[]} practice_projects
 * @property {Timeline} timeline
 * @property {string[]} career_advancement
 */
/**
 * @typedef {object} Timeline
 * @property {string} short_term
 * @property {string} medium_term
 * @property {string} long_term
 */
/**
 * @typedef {object} WritingEvaluationRequest
 * @property {string} prompt
 * @property {string} response
 */
/**
 * @typedef {object} WritingEvaluationResult
 * @property {string} evaluation
 */
/**
 * @typedef {object} WritingPromptResponse
 * @property {string} prompt
 */
/**
 * @typedef {object} WritingRequest
 * @property {string} skills
 * @property {string} job_role
 * @property {string} test_type
 */
/**
 * @typedef {object} LoginRequest
 * @property {string} email
 * @property {string} password
 */
/**
 * @typedef {object} TokenIntrospection
 * @property {boolean} active
 * @property {object} sub
 * @property {object} exp
 * @property {object} roles
 */
/**
 * @typedef {object} TokenPair
 * @property {string} access_token
 * @property {string} refresh_token
 * @property {string} token_type
 */
/**
 * @typedef {object} UserCreate
 * @property {string} email
 * @property {object} name
 * @property {object} phone
 * @property {object} is_active
 * @property {object} is_superuser
 * @property {string} password
 */
/**
 * @typedef {object} UserOut
 * @property {string} email
 * @property {object} name
 * @property {object} phone
 * @property {object} is_active
 * @property {object} is_superuser
 * @property {integer} id
 * @property {string[]} roles
 */
/**
 * @typedef {object} CityCount
 * @property {string} city
 * @property {integer} count
 */
/**
 * @typedef {object} CompanyCreate
 * @property {string} name
 * @property {object} website
 * @property {object} domain
 * @property {object} industry
 * @property {object} size_range
 * @property {object} hq_country
 * @property {object} hq_city
 * @property {object} founded_year
 * @property {object} description
 */
/**
 * @typedef {object} CompanyOut
 * @property {string} name
 * @property {object} website
 * @property {object} domain
 * @property {object} industry
 * @property {object} size_range
 * @property {object} hq_country
 * @property {object} hq_city
 * @property {object} founded_year
 * @property {object} description
 * @property {integer} id
 * @property {string} created_at
 * @property {string} updated_at
 */
/**
 * @typedef {object} CompanyUpdate
 * @property {string} name
 * @property {object} website
 * @property {object} domain
 * @property {object} industry
 * @property {object} size_range
 * @property {object} hq_country
 * @property {object} hq_city
 * @property {object} founded_year
 * @property {object} description
 */
/**
 * @typedef {object} EmploymentType
 */
/**
 * @typedef {object} IndustryCount
 * @property {string} industry
 * @property {integer} count
 */
/**
 * @typedef {object} JobCreate
 * @property {string} title
 * @property {string} description
 * @property {object} company_name
 * @property {object} company_website
 * @property {object} company_id
 * @property {EmploymentType} employment_type
 * @property {WorkType} work_type
 * @property {object} seniority_level
 * @property {object} country
 * @property {object} state
 * @property {object} city
 * @property {object} address
 * @property {object} min_experience_years
 * @property {object} max_experience_years
 * @property {object} skills
 * @property {object} tags
 * @property {object} salary_currency
 * @property {object} salary_min
 * @property {object} salary_max
 * @property {SalaryPeriod} salary_period
 * @property {object} benefits
 * @property {boolean} visa_sponsorship
 * @property {boolean} relocation_assistance
 * @property {object} application_url
 * @property {object} application_email
 * @property {JobStatus} status
 */
/**
 * @typedef {object} JobOut
 * @property {string} title
 * @property {string} description
 * @property {object} company_name
 * @property {object} company_website
 * @property {object} company_id
 * @property {EmploymentType} employment_type
 * @property {WorkType} work_type
 * @property {object} seniority_level
 * @property {object} country
 * @property {object} state
 * @property {object} city
 * @property {object} address
 * @property {object} min_experience_years
 * @property {object} max_experience_years
 * @property {object} skills
 * @property {object} tags
 * @property {object} salary_currency
 * @property {object} salary_min
 * @property {object} salary_max
 * @property {SalaryPeriod} salary_period
 * @property {object} benefits
 * @property {boolean} visa_sponsorship
 * @property {boolean} relocation_assistance
 * @property {object} application_url
 * @property {object} application_email
 * @property {JobStatus} status
 * @property {integer} id
 * @property {string} posted_at
 * @property {string} updated_at
 * @property {boolean} is_deleted
 * @property {object} deleted_at
 * @property {object} company
 */
/**
 * @typedef {object} JobRecommendation
 * @property {string} job_title
 * @property {string} company
 * @property {string} location
 * @property {string} url
 * @property {number} match_score
 * @property {object} salary_min
 * @property {object} salary_max
 * @property {object} created
 * @property {string} description
 * @property {string[]} matched_skills
 */
/**
 * @typedef {object} JobStats
 * @property {StatusCount[]} by_status
 * @property {IndustryCount[]} by_industry
 * @property {CityCount[]} by_city
 */
/**
 * @typedef {object} JobStatus
 */
/**
 * @typedef {object} JobUpdate
 * @property {string} title
 * @property {string} description
 * @property {object} company_name
 * @property {object} company_website
 * @property {object} company_id
 * @property {EmploymentType} employment_type
 * @property {WorkType} work_type
 * @property {object} seniority_level
 * @property {object} country
 * @property {object} state
 * @property {object} city
 * @property {object} address
 * @property {object} min_experience_years
 * @property {object} max_experience_years
 * @property {object} skills
 * @property {object} tags
 * @property {object} salary_currency
 * @property {object} salary_min
 * @property {object} salary_max
 * @property {SalaryPeriod} salary_period
 * @property {object} benefits
 * @property {boolean} visa_sponsorship
 * @property {boolean} relocation_assistance
 * @property {object} application_url
 * @property {object} application_email
 * @property {JobStatus} status
 */
/**
 * @typedef {object} PopulateRequest
 * @property {object} search_terms - Comma-separated skills/keywords to search for
 */
/**
 * @typedef {object} PopulateResponse
 * @property {string} status
 * @property {integer} total_fetched
 * @property {integer} new_jobs_added
 * @property {integer} existing_jobs_updated
 * @property {string} message
 */
/**
 * @typedef {object} RecommendRequest
 * @property {string[]} skills - List of user skills to match against jobs
 */
/**
 * @typedef {object} RecommendResponse
 * @property {object} primary_match
 * @property {object} second_match
 * @property {object} third_match
 * @property {integer} total_jobs_found
 * @property {string[]} skills_searched
 */
/**
 * @typedef {object} SalaryPeriod
 */
/**
 * @typedef {object} SearchRequest
 * @property {string[]} skills - List of user skills to match against jobs
 * @property {object} location - Location to filter jobs (searches city, state, country)
 * @property {object} salary_min - Minimum salary filter
 * @property {object} salary_max - Maximum salary filter
 */
/**
 * @typedef {object} SearchResponse
 * @property {JobRecommendation[]} jobs
 * @property {integer} total_found
 * @property {object} search_criteria
 */
/**
 * @typedef {object} SeniorityLevel
 */
/**
 * @typedef {object} StatusCount
 * @property {string} status
 * @property {integer} count
 */
/**
 * @typedef {object} WorkType
 */
/**
 * @typedef {object} CacheRefreshResponse
 * @property {boolean} success - Request success status
 * @property {string} message - Response message
 * @property {string} timestamp - Response timestamp
 */
/**
 * @typedef {object} NewsCategory
 */
/**
 * @typedef {object} NewsItem
 * @property {object} id
 * @property {string} title - News title
 * @property {object} description - News description
 * @property {string} url - News URL
 * @property {string} source_name - Source name
 * @property {NewsCategory} category - News category
 * @property {object} published_at - Publication date
 * @property {object} image_url - Image URL
 * @property {object} author - Author name
 * @property {object} relevance_score - Relevance score
 */
/**
 * @typedef {object} NewsResponse
 * @property {boolean} success - Request success status
 * @property {NewsItem[]} data - News items
 * @property {integer} count - Number of news items
 * @property {boolean} cached - Whether data is from cache
 * @property {string} timestamp - Response timestamp
 */
/**
 * @typedef {object} NewsSummaryResponse
 * @property {boolean} success - Request success status
 * @property {object} data - Summary data
 * @property {string} timestamp - Response timestamp
 */
/**
 * @typedef {object} AvailabilityIn
 * @property {string} starts_at
 * @property {string} ends_at
 * @property {object} is_recurring
 * @property {object} rrule
 */
/**
 * @typedef {object} AvailabilityOut
 * @property {string} starts_at
 * @property {string} ends_at
 * @property {object} is_recurring
 * @property {object} rrule
 * @property {integer} id
 * @property {integer} mentor_id
 */
/**
 * @typedef {object} GoalIn
 * @property {integer} skill_id
 * @property {integer} priority
 * @property {object} target_date
 * @property {object} notes
 */
/**
 * @typedef {object} GoalOut
 * @property {integer} skill_id
 * @property {integer} priority
 * @property {object} target_date
 * @property {object} notes
 * @property {integer} id
 * @property {integer} mentee_id
 * @property {string} status
 */
/**
 * @typedef {object} GoalStatusDecisionIn
 * @property {boolean} approve
 * @property {object} comment
 */
/**
 * @typedef {object} GoalStatusRequestIn
 * @property {string} requested_status
 * @property {object} notes
 */
/**
 * @typedef {object} GoalStatusRequestOut
 * @property {integer} id
 * @property {integer} goal_id
 * @property {integer} mentee_id
 * @property {string} requested_status
 * @property {object} notes
 * @property {string} state
 * @property {object} decided_by
 * @property {object} decided_comment
 * @property {object} decided_at
 */
/**
 * @typedef {object} MentorScoreIn
 * @property {integer} score
 * @property {object} notes
 */
/**
 * @typedef {object} MentorScoreOut
 * @property {integer} id
 * @property {integer} session_id
 * @property {integer} mentor_id
 * @property {integer} mentee_id
 * @property {integer} score
 * @property {object} notes
 */
/**
 * @typedef {object} MentorSkillIn
 * @property {integer} skill_id
 * @property {integer} level
 * @property {integer} years
 */
/**
 * @typedef {object} MentorSkillOut
 * @property {integer} skill_id
 * @property {integer} level
 * @property {integer} years
 * @property {integer} mentor_id
 */
/**
 * @typedef {object} ProfileOut
 * @property {object} name
 * @property {object} email
 * @property {object} phone_number
 * @property {object} specialization
 * @property {object} graduation_year
 * @property {object} job_type_preference
 * @property {object} preferred_locations
 * @property {object} aspiring_companies
 * @property {object} career_goal
 * @property {integer} id
 * @property {integer} auth_user_id
 * @property {string} created_at
 * @property {string} updated_at
 * @property {SkillOut[]} skills
 * @property {AssessmentOut[]} latest_assessments
 * @property {AssessmentOut[]} top_assessments
 * @property {object} idp
 * @property {object} learning_paths
 */
/**
 * @typedef {object} ProfileUpdate
 * @property {object} name
 * @property {object} email
 * @property {object} phone_number
 * @property {object} specialization
 * @property {object} graduation_year
 * @property {object} job_type_preference
 * @property {object} preferred_locations
 * @property {object} aspiring_companies
 * @property {object} career_goal
 */
/**
 * @typedef {object} RatingsSummaryOut
 * @property {integer} target_id
 * @property {string} kind
 * @property {number} average
 * @property {integer} count
 * @property {object} distribution
 */
/**
 * @typedef {object} ReviewIn
 * @property {integer} rating
 * @property {object} text
 */
/**
 * @typedef {object} SessionIn
 * @property {integer} mentor_id
 * @property {string} starts_at
 * @property {string} ends_at
 * @property {object} agenda
 */
/**
 * @typedef {object} SessionOut
 * @property {integer} mentor_id
 * @property {string} starts_at
 * @property {string} ends_at
 * @property {object} agenda
 * @property {integer} id
 * @property {integer} mentee_id
 * @property {string} status
 */
/**
 * @typedef {object} SessionStatusUpdateIn
 * @property {string} status
 */
/**
 * @typedef {object} SessionStatusUpdateOut
 * @property {integer} id
 * @property {string} status
 */
/**
 * @typedef {object} SkillBase
 * @property {string} name
 * @property {object} category
 */
/**
 * @typedef {object} SkillOut
 * @property {string} skill
 * @property {object} score
 * @property {object} source
 * @property {integer} id
 * @property {object} last_updated
 */
/**
 * @typedef {object} Body_record_audio_v1_audio_record_post
 * @property {string} audio
 * @property {number} duration
 */
/**
 * @typedef {object} Body_transcribe_audio_file_v1_audio_transcribe_post
 * @property {string} file
 */
/**
 * @typedef {object} CompanyTemplate
 */
/**
 * @typedef {object} DifficultyLevel
 */
/**
 * @typedef {object} FrameAnalysisRequest
 * @property {string} frame_data
 * @property {object} session_id
 */
/**
 * @typedef {object} FrameAnalysisResponse
 * @property {object} posture
 * @property {object} eye_contact
 * @property {object} facial_expression
 * @property {object} hand_gestures
 * @property {object} head_movement
 * @property {number} overall_score
 * @property {number} confidence_score
 * @property {string[]} real_time_suggestions
 * @property {number} timestamp
 */
/**
 * @typedef {object} HealthResponse
 * @property {string} status
 * @property {string} version
 * @property {object} services
 */
/**
 * @typedef {object} IndustryType
 */
/**
 * @typedef {object} InterviewMode
 */
/**
 * @typedef {object} InterviewReplyRequest
 * @property {string} session_id
 * @property {string} user_response
 * @property {object} input_method
 */
/**
 * @typedef {object} InterviewReplyResponse
 * @property {string} next_question
 * @property {object} feedback
 * @property {boolean} is_final
 * @property {object} analysis
 * @property {object} real_time_feedback
 */
/**
 * @typedef {object} InterviewStartRequest
 * @property {InterviewType} interview_type
 * @property {string} position
 * @property {DifficultyLevel} experience_level
 * @property {object} preferred_language
 * @property {InterviewMode} mode
 * @property {IndustryType} industry
 * @property {object} company_template
 * @property {object} custom_instructions
 * @property {object} user_id
 * @property {ResumeDataSchema} resume_data
 */
/**
 * @typedef {object} InterviewStartResponse
 * @property {string} session_id
 * @property {string} first_question
 * @property {InterviewType} interview_type
 * @property {InterviewMode} mode
 * @property {object} template_info
 */
/**
 * @typedef {object} InterviewType
 */
/**
 * @typedef {object} RoleSuggestion
 * @property {string} role
 * @property {string} description
 * @property {string} match_reason
 */
/**
 * @typedef {object} RoleSuggestionsRequest
 * @property {ResumeDataSchema} resume_data
 */
/**
 * @typedef {object} RoleSuggestionsResponse
 * @property {boolean} success
 * @property {RoleSuggestion[]} roles
 */
/**
 * @typedef {object} AssessmentIn
 * @property {object} assessment_id
 * @property {object} assessment_type
 * @property {object} score
 * @property {object} taken_at
 * @property {object} summary
 */
/**
 * @typedef {object} AssessmentOut
 * @property {object} assessment_id
 * @property {object} assessment_type
 * @property {object} score
 * @property {object} taken_at
 * @property {object} summary
 * @property {integer} id
 * @property {string} created_at
 */
/**
 * @typedef {object} IDPBenchmarkRow
 * @property {string} group
 * @property {number} avg_overall
 * @property {integer} count
 */
/**
 * @typedef {object} IDPEvent
 * @property {string} type
 * @property {number} value
 * @property {object} taken_at
 * @property {object} meta
 */
/**
 * @typedef {object} IDPOut
 * @property {object} completion_percentage
 * @property {object} recommended_courses_completion
 * @property {object} mentor_rating
 * @property {object} collaboration_score
 * @property {object} projects_score
 * @property {integer} id
 * @property {integer} auth_user_id
 * @property {string} updated_at
 */
/**
 * @typedef {object} IDPPatch
 * @property {object} completion_percentage
 * @property {object} recommended_courses_completion
 * @property {object} mentor_rating
 * @property {object} collaboration_score
 * @property {object} projects_score
 */
/**
 * @typedef {object} IDPPut
 * @property {object} completion_percentage
 * @property {object} recommended_courses_completion
 * @property {object} mentor_rating
 * @property {object} collaboration_score
 * @property {object} projects_score
 */
/**
 * @typedef {object} IDPSummaryOut
 * @property {object} completion_percentage
 * @property {object} recommended_courses_completion
 * @property {object} mentor_rating
 * @property {object} collaboration_score
 * @property {object} projects_score
 * @property {object} overall_score
 */
/**
 * @typedef {object} IDPWeightsOut
 * @property {number} mentor
 * @property {number} projects
 * @property {number} collab
 * @property {number} courses
 */
/**
 * @typedef {object} LPSkillIn
 * @property {string} skill
 * @property {object} progress_percent
 * @property {object} target_percent
 * @property {object} source
 * @property {object} started_at
 */
/**
 * @typedef {object} LPSkillOut
 * @property {integer} id
 * @property {integer} path_id
 * @property {string} skill
 * @property {number} progress_percent
 * @property {number} target_percent
 * @property {object} source
 * @property {object} started_at
 * @property {string} updated_at
 */
/**
 * @typedef {object} LPSkillPatch
 * @property {object} progress_percent
 * @property {object} target_percent
 * @property {object} source
 * @property {object} started_at
 */
/**
 * @typedef {object} LPSnapshotOut
 * @property {app__schemas__LearningPathOut__2} path
 * @property {LPSkillOut[]} skills_in_progress
 */
/**
 * @typedef {object} LearningPathCreate
 * @property {string} name
 * @property {object} description
 * @property {object} is_active
 */
/**
 * @typedef {object} LearningPathUpdate
 * @property {object} name
 * @property {object} description
 * @property {object} is_active
 */
/**
 * @typedef {object} ProfileCreate
 * @property {object} name
 * @property {object} email
 * @property {object} phone_number
 * @property {object} specialization
 * @property {object} graduation_year
 * @property {object} job_type_preference
 * @property {object} preferred_locations
 * @property {object} aspiring_companies
 * @property {object} career_goal
 */
/**
 * @typedef {object} SkillIn
 * @property {string} skill
 * @property {object} score
 * @property {object} source
 */
/**
 * @typedef {object} app__schemas__LearningPathOut__1
 * @property {integer} id
 * @property {string} title
 * @property {object} description
 */
/**
 * @typedef {object} app__schemas__LearningPathOut__2
 * @property {integer} id
 * @property {integer} auth_user_id
 * @property {string} name
 * @property {object} description
 * @property {boolean} is_active
 * @property {string} created_at
 * @property {string} updated_at
 * @property {object} completion_percentage
 */

// --- Generated React Query Hooks ---

/**
 * @description Hook for /resumes/api/v1/resumes [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeRead[]>}
 */
export const listResumesApiV1ResumesGet = (options) => {
  const queryKey = ['list_resumes_api_v1_resumes_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/api/v1/resumes'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes [POST]
 * @param {Body_upload_resume_api_v1_resumes_post} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ResumeRead, unknown, Body_upload_resume_api_v1_resumes_post>}
 */
export const uploadResumeApiV1ResumesPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/resumes/api/v1/resumes', data, 'multipart/form-data'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeRead>}
 */
export const getResumeApiV1Resumes_ResumeId_Get = (options) => {
  const resume_id = options?.resume_id;
  const queryKey = ['get_resume_api_v1_resumes__resume_id__get', resume_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/resumes/api/v1/resumes/${resume_id}`),
    enabled: !!resume_id,
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const deleteResumeApiV1Resumes_ResumeId_Delete = (options) => {
  return useMutation({
    mutationFn: ({ resume_id, ...data }) => apiClient('delete', `/resumes/api/v1/resumes/${resume_id}`, data),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id}/analysis [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeAnalysis>}
 */
export const getAnalysisApiV1Resumes_ResumeId_AnalysisGet = (options) => {
  const resume_id = options?.resume_id;
  const queryKey = ['get_analysis_api_v1_resumes__resume_id__analysis_get', resume_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/resumes/api/v1/resumes/${resume_id}/analysis`),
    enabled: !!resume_id,
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id}/re-analyze [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ResumeAnalysis, unknown, void>}
 */
export const reanalyzeApiV1Resumes_ResumeId_ReAnalyzePost = (options) => {
  return useMutation({
    mutationFn: ({ resume_id, ...data }) => apiClient('post', `/resumes/api/v1/resumes/${resume_id}/re-analyze`, data),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/admin/all [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeRead[]>}
 */
export const adminListAllApiV1ResumesAdminAllGet = (options) => {
  const queryKey = ['admin_list_all_api_v1_resumes_admin_all_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/api/v1/resumes/admin/all'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/builder/parse [POST]
 * @param {Body_parse_resume_builder_api_v1_resumes_builder_parse_post} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ResumeParseResponseSchema, unknown, Body_parse_resume_builder_api_v1_resumes_builder_parse_post>}
 */
export const parseResumeBuilderApiV1ResumesBuilderParsePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/resumes/api/v1/resumes/builder/parse', data, 'multipart/form-data'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/builder/generate [POST]
 * @param {ResumeGenerateRequestSchema} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ResumeGenerateResponseSchema, unknown, ResumeGenerateRequestSchema>}
 */
export const generateResumeBuilderApiV1ResumesBuilderGeneratePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/resumes/api/v1/resumes/builder/generate', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/builder/export/pdf [POST]
 * @param {ExportRequestSchema} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, ExportRequestSchema>}
 */
export const exportPdfBuilderApiV1ResumesBuilderExportPdfPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/resumes/api/v1/resumes/builder/export/pdf', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/builder/export/docx [POST]
 * @param {ExportRequestSchema} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, ExportRequestSchema>}
 */
export const exportDocxBuilderApiV1ResumesBuilderExportDocxPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/resumes/api/v1/resumes/builder/export/docx', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const resumesRoot_Get = (options) => {
  const queryKey = ['resumes_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const resumesHealthCheckHealthGet = (options) => {
  const queryKey = ['resumes_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/health'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const resumesHealthzHealthzGet = (options) => {
  const queryKey = ['resumes_healthz_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/healthz'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_aptitude [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<GenerateResponse, unknown, void>}
 */
export const generateQuestionsV1GenerateAptitudePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_aptitude', data),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/evaluate_aptitude [POST]
 * @param {EvaluateByIdsRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<EvaluateResponse, unknown, EvaluateByIdsRequest>}
 */
export const evaluateAnswersV1EvaluateAptitudePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/evaluate_aptitude', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_challenge [POST]
 * @param {ChallengeRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ChallengeResponse, unknown, ChallengeRequest>}
 */
export const generateRandomCodingChallengeV1GenerateChallengePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_challenge', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/evaluate_code [POST]
 * @param {CodeEvaluationRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CodeEvaluationResponse, unknown, CodeEvaluationRequest>}
 */
export const evaluateCodeSolutionV1EvaluateCodePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/evaluate_code', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_mcq [POST]
 * @param {MCQRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<MCQResponse, unknown, MCQRequest>}
 */
export const generateMcqQuestionsV1GenerateMcqPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_mcq', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_behavioral_questions [POST]
 * @param {BehavioralRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<MCQResponse, unknown, BehavioralRequest>}
 */
export const generateBehavioralQuestionsV1GenerateBehavioralQuestionsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_behavioral_questions', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/evaluate_behavioral [POST]
 * @param {BehavioralEvaluationRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<BehavioralEvaluationResult, unknown, BehavioralEvaluationRequest>}
 */
export const evaluateBehavioralResponseV1EvaluateBehavioralPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/evaluate_behavioral', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_writing_prompt [POST]
 * @param {WritingRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<WritingPromptResponse, unknown, WritingRequest>}
 */
export const generateWritingPromptV1GenerateWritingPromptPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_writing_prompt', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/evaluate_writing [POST]
 * @param {WritingEvaluationRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<WritingEvaluationResult, unknown, WritingEvaluationRequest>}
 */
export const evaluateWritingResponseV1EvaluateWritingPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/evaluate_writing', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/analyze_performance_gaps [POST]
 * @param {PerformanceGapsRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<PerformanceGapsResponse, unknown, PerformanceGapsRequest>}
 */
export const analyzePerformanceGapsV1AnalyzePerformanceGapsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/analyze_performance_gaps', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_skill_based_recommendations [POST]
 * @param {SkillRecommendationsRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<SkillRecommendationsResponse, unknown, SkillRecommendationsRequest>}
 */
export const generateSkillBasedRecommendationsV1GenerateSkillBasedRecommendationsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_skill_based_recommendations', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/download-report [POST]
 * @param {ReportRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ReportResponse, unknown, ReportRequest>}
 */
export const downloadReportV1DownloadReportPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/download-report', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_interview_pdf [POST]
 * @param {InterviewPDFRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<InterviewPDFResponse, unknown, InterviewPDFRequest>}
 */
export const generateInterviewPdfV1GenerateInterviewPdfPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_interview_pdf', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/generate_company_question [POST]
 * @param {CompanyQuestionRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyQuestionResponse, unknown, CompanyQuestionRequest>}
 */
export const generateCompanyQuestionV1GenerateCompanyQuestionPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/generate_company_question', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/evaluate_company_answer [POST]
 * @param {CompanyAnswerRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyAnswerEvaluationResponse, unknown, CompanyAnswerRequest>}
 */
export const evaluateCompanyAnswerV1EvaluateCompanyAnswerPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/evaluate_company_answer', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/coding/generate_question [POST]
 * @param {CodingProfile} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CodingQuestionsResponse, unknown, CodingProfile>}
 */
export const generateQuestionV1CodingGenerateQuestionPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/v1/coding/generate_question', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const quizRoot_Get = (options) => {
  const queryKey = ['quiz_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/quiz/'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const quizHealthCheckV1HealthGet = (options) => {
  const queryKey = ['quiz_health_check_v1_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/quiz/v1/health'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/v1/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const quizHealthzV1HealthzGet = (options) => {
  const queryKey = ['quiz_healthz_v1_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/quiz/v1/healthz'),
    ...options,
  });
};

/**
 * @description Hook for /auth/register [POST]
 * @param {UserCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<UserOut, unknown, UserCreate>}
 */
export const registerRegisterPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/register', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /auth/login [POST]
 * @param {LoginRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<TokenPair, unknown, LoginRequest>}
 */
export const loginLoginPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/login', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /auth/refresh [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<TokenPair, unknown, void>}
 */
export const refreshTokenRefreshPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/refresh', data),
    ...options,
  });
};

/**
 * @description Hook for /auth/me [GET]
 * @returns {import('@tanstack/react-query').QueryResult<UserOut>}
 */
export const authMeMeGet = (options) => {
  const queryKey = ['auth_me_me_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/auth/me'),
    ...options,
  });
};

/**
 * @description Hook for /auth/introspect [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<TokenIntrospection, unknown, void>}
 */
export const introspectIntrospectPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/introspect', data),
    ...options,
  });
};

/**
 * @description Hook for /auth/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const authRoot_Get = (options) => {
  const queryKey = ['auth_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/auth/'),
    ...options,
  });
};

/**
 * @description Hook for /auth/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const authHealthCheckHealthGet = (options) => {
  const queryKey = ['auth_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/auth/health'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies [GET]
 * @returns {import('@tanstack/react-query').QueryResult<CompanyOut[]>}
 */
export const listCompaniesApiV1CompaniesGet = (options) => {
  const queryKey = ['list_companies_api_v1_companies_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/api/v1/companies'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies [POST]
 * @param {CompanyCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyOut, unknown, CompanyCreate>}
 */
export const createCompanyApiV1CompaniesPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/jobs/api/v1/companies', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies/{company_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<CompanyOut>}
 */
export const getCompanyApiV1Companies_CompanyId_Get = (options) => {
  const company_id = options?.company_id;
  const queryKey = ['get_company_api_v1_companies__company_id__get', company_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/jobs/api/v1/companies/${company_id}`),
    enabled: !!company_id,
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies/{company_id} [PUT]
 * @param {CompanyUpdate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyOut, unknown, CompanyUpdate>}
 */
export const updateCompanyApiV1Companies_CompanyId_Put = (options) => {
  return useMutation({
    mutationFn: ({ company_id, ...data }) => apiClient('put', `/jobs/api/v1/companies/${company_id}`, data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies/{company_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const deleteCompanyApiV1Companies_CompanyId_Delete = (options) => {
  return useMutation({
    mutationFn: ({ company_id, ...data }) => apiClient('delete', `/jobs/api/v1/companies/${company_id}`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/stats [GET]
 * @returns {import('@tanstack/react-query').QueryResult<JobStats>}
 */
export const jobsStatsApiV1JobsStatsGet = (options) => {
  const queryKey = ['jobs_stats_api_v1_jobs_stats_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/api/v1/jobs/stats'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs [GET]
 * @returns {import('@tanstack/react-query').QueryResult<JobOut[]>}
 */
export const listJobsApiV1JobsGet = (options) => {
  const queryKey = ['list_jobs_api_v1_jobs_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/api/v1/jobs'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs [POST]
 * @param {JobCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<JobOut, unknown, JobCreate>}
 */
export const createJobApiV1JobsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/jobs/api/v1/jobs', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<JobOut>}
 */
export const getJobApiV1Jobs_JobId_Get = (options) => {
  const job_id = options?.job_id;
  const queryKey = ['get_job_api_v1_jobs__job_id__get', job_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/jobs/api/v1/jobs/${job_id}`),
    enabled: !!job_id,
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id} [PUT]
 * @param {JobUpdate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<JobOut, unknown, JobUpdate>}
 */
export const updateJobApiV1Jobs_JobId_Put = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('put', `/jobs/api/v1/jobs/${job_id}`, data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const deleteJobApiV1Jobs_JobId_Delete = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('delete', `/jobs/api/v1/jobs/${job_id}`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id}/restore [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<JobOut, unknown, void>}
 */
export const restoreJobApiV1Jobs_JobId_RestorePost = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('post', `/jobs/api/v1/jobs/${job_id}/restore`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id}/audits [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object[]>}
 */
export const listJobAuditsApiV1Jobs_JobId_AuditsGet = (options) => {
  const job_id = options?.job_id;
  const queryKey = ['list_job_audits_api_v1_jobs__job_id__audits_get', job_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/jobs/api/v1/jobs/${job_id}/audits`),
    enabled: !!job_id,
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id}/hard-delete [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const hardDeleteJobApiV1Jobs_JobId_HardDeleteDelete = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('delete', `/jobs/api/v1/jobs/${job_id}/hard-delete`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/listings/recommend [POST]
 * @param {RecommendRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<RecommendResponse, unknown, RecommendRequest>}
 */
export const recommendJobsApiV1ListingsRecommendPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/jobs/api/v1/listings/recommend', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/listings/search [POST]
 * @param {SearchRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<SearchResponse, unknown, SearchRequest>}
 */
export const searchJobsApiV1ListingsSearchPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/jobs/api/v1/listings/search', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/listings/populate [POST]
 * @param {PopulateRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<PopulateResponse, unknown, PopulateRequest>}
 */
export const populateDatabaseApiV1ListingsPopulatePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/jobs/api/v1/listings/populate', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const jobsRoot_Get = (options) => {
  const queryKey = ['jobs_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const jobsHealthCheckHealthGet = (options) => {
  const queryKey = ['jobs_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/health'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const jobsHealthzHealthzGet = (options) => {
  const queryKey = ['jobs_healthz_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/healthz'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/latest [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getLatestNewsApiV1NewsLatestGet = (options) => {
  const queryKey = ['get_latest_news_api_v1_news_latest_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/latest'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/category/{category} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getNewsByCategoryApiV1NewsCategory_Category_Get = (options) => {
  const queryKey = ['get_news_by_category_api_v1_news_category__category__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/category/{category}'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/source/{source_name} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getNewsBySourceApiV1NewsSource_SourceName_Get = (options) => {
  const queryKey = ['get_news_by_source_api_v1_news_source__source_name__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/source/{source_name}'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/search [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const searchNewsApiV1NewsSearchGet = (options) => {
  const queryKey = ['search_news_api_v1_news_search_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/search'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/summary [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsSummaryResponse>}
 */
export const getNewsSummaryApiV1NewsSummaryGet = (options) => {
  const queryKey = ['get_news_summary_api_v1_news_summary_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/summary'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/refresh [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CacheRefreshResponse, unknown, void>}
 */
export const refreshNewsCacheApiV1NewsRefreshPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/news/api/v1/news/refresh', data),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/trending [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getTrendingNewsApiV1NewsTrendingGet = (options) => {
  const queryKey = ['get_trending_news_api_v1_news_trending_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/trending'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/proxy/image [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const proxyImageApiV1NewsProxyImageGet = (options) => {
  const queryKey = ['proxy_image_api_v1_news_proxy_image_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/proxy/image'),
    ...options,
  });
};

/**
 * @description Hook for /news/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const newsRoot_Get = (options) => {
  const queryKey = ['news_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/'),
    ...options,
  });
};

/**
 * @description Hook for /news/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const newsHealthCheckHealthGet = (options) => {
  const queryKey = ['news_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/health'),
    ...options,
  });
};

/**
 * @description Hook for /news/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const newsHealthzHealthzGet = (options) => {
  const queryKey = ['news_healthz_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/healthz'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ProfileOut>}
 */
export const meV1MeGet = (options) => {
  const queryKey = ['me_v1_me_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/me'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me [PATCH]
 * @param {ProfileUpdate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ProfileOut, unknown, ProfileUpdate>}
 */
export const updateMeV1MePatch = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('patch', '/mentorship/v1/me', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/skills [GET]
 * @returns {import('@tanstack/react-query').QueryResult<SkillOut[]>}
 */
export const listSkillsV1SkillsGet = (options) => {
  const queryKey = ['list_skills_v1_skills_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/skills'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/skills [POST]
 * @param {SkillBase} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<SkillOut, unknown, SkillBase>}
 */
export const createSkillV1SkillsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/skills', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentor/skills [GET]
 * @returns {import('@tanstack/react-query').QueryResult<MentorSkillOut[]>}
 */
export const myMentorSkillsV1MeMentorSkillsGet = (options) => {
  const queryKey = ['my_mentor_skills_v1_me_mentor_skills_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/me/mentor/skills'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentor/skills [POST]
 * @param {MentorSkillIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<MentorSkillOut, unknown, MentorSkillIn>}
 */
export const addMentorSkillV1MeMentorSkillsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/me/mentor/skills', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentor/skills/{skill_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const deleteMentorSkillV1MeMentorSkills_SkillId_Delete = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('delete', '/mentorship/v1/me/mentor/skills/{skill_id}', data),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentee/goals [GET]
 * @returns {import('@tanstack/react-query').QueryResult<GoalOut[]>}
 */
export const myGoalsV1MeMenteeGoalsGet = (options) => {
  const queryKey = ['my_goals_v1_me_mentee_goals_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/me/mentee/goals'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentee/goals [POST]
 * @param {GoalIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<GoalOut, unknown, GoalIn>}
 */
export const addGoalV1MeMenteeGoalsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/me/mentee/goals', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentee/goals/{goal_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const deleteGoalV1MeMenteeGoals_GoalId_Delete = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('delete', '/mentorship/v1/me/mentee/goals/{goal_id}', data),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentee/goals/{goal_id}/request-status [POST]
 * @param {GoalStatusRequestIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<GoalStatusRequestOut, unknown, GoalStatusRequestIn>}
 */
export const requestGoalStatusChangeV1MeMenteeGoals_GoalId_RequestStatusPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/me/mentee/goals/{goal_id}/request-status', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/goals/status-requests/pending [GET]
 * @returns {import('@tanstack/react-query').QueryResult<GoalStatusRequestOut[]>}
 */
export const listPendingGoalStatusRequestsV1GoalsStatusRequestsPendingGet = (options) => {
  const queryKey = ['list_pending_goal_status_requests_v1_goals_status_requests_pending_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/goals/status-requests/pending'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/goals/{goal_id}/status-requests/{request_id}/decision [POST]
 * @param {GoalStatusDecisionIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<GoalStatusRequestOut, unknown, GoalStatusDecisionIn>}
 */
export const decideGoalStatusRequestV1Goals_GoalId_StatusRequests_RequestId_DecisionPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/goals/{goal_id}/status-requests/{request_id}/decision', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/mentors/search [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const mentorSearchV1MentorsSearchGet = (options) => {
  const queryKey = ['mentor_search_v1_mentors_search_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/mentors/search'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/mentors/{mentor_id}/availability [GET]
 * @returns {import('@tanstack/react-query').QueryResult<AvailabilityOut[]>}
 */
export const listAvailabilityV1Mentors_MentorId_AvailabilityGet = (options) => {
  const queryKey = ['list_availability_v1_mentors__mentor_id__availability_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/mentors/{mentor_id}/availability'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/me/mentor/availability [POST]
 * @param {AvailabilityIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<AvailabilityOut, unknown, AvailabilityIn>}
 */
export const createAvailabilityV1MeMentorAvailabilityPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/me/mentor/availability', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/sessions [GET]
 * @returns {import('@tanstack/react-query').QueryResult<SessionOut[]>}
 */
export const listSessionsV1SessionsGet = (options) => {
  const queryKey = ['list_sessions_v1_sessions_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/sessions'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/sessions [POST]
 * @param {SessionIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<SessionOut, unknown, SessionIn>}
 */
export const bookSessionV1SessionsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/sessions', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/sessions/{session_id} [PATCH]
 * @param {SessionStatusUpdateIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<SessionStatusUpdateOut, unknown, SessionStatusUpdateIn>}
 */
export const updateSessionV1Sessions_SessionId_Patch = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('patch', '/mentorship/v1/sessions/{session_id}', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/sessions/{session_id}/review [POST]
 * @param {ReviewIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, ReviewIn>}
 */
export const createReviewV1Sessions_SessionId_ReviewPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/sessions/{session_id}/review', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/sessions/{session_id}/mentor-score [POST]
 * @param {MentorScoreIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<MentorScoreOut, unknown, MentorScoreIn>}
 */
export const mentorScoreV1Sessions_SessionId_MentorScorePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/mentorship/v1/sessions/{session_id}/mentor-score', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/mentors/{mentor_id}/ratings [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RatingsSummaryOut>}
 */
export const mentorRatingsV1Mentors_MentorId_RatingsGet = (options) => {
  const queryKey = ['mentor_ratings_v1_mentors__mentor_id__ratings_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/mentors/{mentor_id}/ratings'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/mentees/{mentee_id}/scores [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RatingsSummaryOut>}
 */
export const menteeScoresV1Mentees_MenteeId_ScoresGet = (options) => {
  const queryKey = ['mentee_scores_v1_mentees__mentee_id__scores_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/mentees/{mentee_id}/scores'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const mentorshipRoot_Get = (options) => {
  const queryKey = ['mentorship_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const mentorshipHealthCheckV1HealthGet = (options) => {
  const queryKey = ['mentorship_health_check_v1_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/health'),
    ...options,
  });
};

/**
 * @description Hook for /mentorship/v1/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const mentorshipHealthzV1HealthzGet = (options) => {
  const queryKey = ['mentorship_healthz_v1_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/mentorship/v1/healthz'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/interview/suggest-roles [POST]
 * @param {RoleSuggestionsRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<RoleSuggestionsResponse, unknown, RoleSuggestionsRequest>}
 */
export const suggestRolesV1InterviewSuggestRolesPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/interview/v1/interview/suggest-roles', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/interview/start [POST]
 * @param {InterviewStartRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<InterviewStartResponse, unknown, InterviewStartRequest>}
 */
export const startInterviewV1InterviewStartPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/interview/v1/interview/start', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/interview/{session_id}/history [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getConversationHistoryV1Interview_SessionId_HistoryGet = (options) => {
  const queryKey = ['get_conversation_history_v1_interview__session_id__history_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/interview/{session_id}/history'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/interview/reply [POST]
 * @param {InterviewReplyRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<InterviewReplyResponse, unknown, InterviewReplyRequest>}
 */
export const submitReplyV1InterviewReplyPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/interview/v1/interview/reply', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/interview/analysis/{session_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getInterviewAnalysisV1InterviewAnalysis_SessionId_Get = (options) => {
  const queryKey = ['get_interview_analysis_v1_interview_analysis__session_id__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/interview/analysis/{session_id}'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/analyze/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const analysisHealthV1AnalyzeHealthGet = (options) => {
  const queryKey = ['analysis_health_v1_analyze_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/analyze/health'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/analyze/frame [POST]
 * @param {FrameAnalysisRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<FrameAnalysisResponse, unknown, FrameAnalysisRequest>}
 */
export const analyzeFrameV1AnalyzeFramePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/interview/v1/analyze/frame', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/analyze/session/{session_id}/metrics [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getSessionMetricsV1AnalyzeSession_SessionId_MetricsGet = (options) => {
  const queryKey = ['get_session_metrics_v1_analyze_session__session_id__metrics_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/analyze/session/{session_id}/metrics'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/analyze/session/{session_id}/trends [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getPerformanceTrendsV1AnalyzeSession_SessionId_TrendsGet = (options) => {
  const queryKey = ['get_performance_trends_v1_analyze_session__session_id__trends_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/analyze/session/{session_id}/trends'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/user/{user_id}/profile [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getUserProfileV1User_UserId_ProfileGet = (options) => {
  const queryKey = ['get_user_profile_v1_user__user_id__profile_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/user/{user_id}/profile'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/user/{user_id}/profile [POST]
 * @param {object} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, object>}
 */
export const updateUserProfileV1User_UserId_ProfilePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/interview/v1/user/{user_id}/profile', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/user/{user_id}/progress [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getUserProgressV1User_UserId_ProgressGet = (options) => {
  const queryKey = ['get_user_progress_v1_user__user_id__progress_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/user/{user_id}/progress'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/user/{user_id}/recommendations [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getUserRecommendationsV1User_UserId_RecommendationsGet = (options) => {
  const queryKey = ['get_user_recommendations_v1_user__user_id__recommendations_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/user/{user_id}/recommendations'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/user/{user_id}/history [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getUserHistoryV1User_UserId_HistoryGet = (options) => {
  const queryKey = ['get_user_history_v1_user__user_id__history_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/user/{user_id}/history'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/audio/devices [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getAudioDevicesV1AudioDevicesGet = (options) => {
  const queryKey = ['get_audio_devices_v1_audio_devices_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/audio/devices'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/audio/record [POST]
 * @param {Body_record_audio_v1_audio_record_post} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, Body_record_audio_v1_audio_record_post>}
 */
export const recordAudioV1AudioRecordPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/interview/v1/audio/record', data, 'multipart/form-data'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/audio/transcribe [POST]
 * @param {Body_transcribe_audio_file_v1_audio_transcribe_post} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, Body_transcribe_audio_file_v1_audio_transcribe_post>}
 */
export const transcribeAudioFileV1AudioTranscribePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/interview/v1/audio/transcribe', data, 'multipart/form-data'),
    ...options,
  });
};

/**
 * @description Hook for /interview/v1/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthResponse>}
 */
export const healthCheckV1HealthGet = (options) => {
  const queryKey = ['health_check_v1_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/interview/v1/health'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/profiles/me [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ProfileOut>}
 */
export const getMeV1ProfilesMeGet = (options) => {
  const queryKey = ['get_me_v1_profiles_me_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/profiles/me'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/profiles [POST]
 * @param {ProfileCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ProfileOut, unknown, ProfileCreate>}
 */
export const upsertProfileV1ProfilesPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/profile/v1/profiles', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/profiles [PATCH]
 * @param {ProfileUpdate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ProfileOut, unknown, ProfileUpdate>}
 */
export const patchProfileV1ProfilesPatch = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('patch', '/profile/v1/profiles', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/skills [GET]
 * @returns {import('@tanstack/react-query').QueryResult<SkillOut[]>}
 */
export const profileListSkillsV1SkillsGet = (options) => {
  const queryKey = ['profile_list_skills_v1_skills_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/skills'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/skills [PUT]
 * @param {SkillIn[]} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<SkillOut[], unknown, SkillIn[]>}
 */
export const bulkUpsertSkillsV1SkillsPut = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('put', '/profile/v1/skills', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/assessments [POST]
 * @param {AssessmentIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<AssessmentOut, unknown, AssessmentIn>}
 */
export const addAssessmentV1AssessmentsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/profile/v1/assessments', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/assessments/latest [GET]
 * @returns {import('@tanstack/react-query').QueryResult<AssessmentOut[]>}
 */
export const latestV1AssessmentsLatestGet = (options) => {
  const queryKey = ['latest_v1_assessments_latest_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/assessments/latest'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/assessments/top [GET]
 * @returns {import('@tanstack/react-query').QueryResult<AssessmentOut[]>}
 */
export const topV1AssessmentsTopGet = (options) => {
  const queryKey = ['top_v1_assessments_top_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/assessments/top'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/idp/weights [GET]
 * @returns {import('@tanstack/react-query').QueryResult<IDPWeightsOut>}
 */
export const getWeightsV1IdpWeightsGet = (options) => {
  const queryKey = ['get_weights_v1_idp_weights_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/idp/weights'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/idp/me [GET]
 * @returns {import('@tanstack/react-query').QueryResult<IDPOut>}
 */
export const getMyIdpV1IdpMeGet = (options) => {
  const queryKey = ['get_my_idp_v1_idp_me_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/idp/me'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/idp/{auth_user_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<IDPOut>}
 */
export const getIdpForUserV1Idp_AuthUserId_Get = (options) => {
  const queryKey = ['get_idp_for_user_v1_idp__auth_user_id__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/idp/{auth_user_id}'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/idp [PUT]
 * @param {IDPPut} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<IDPOut, unknown, IDPPut>}
 */
export const putIdpV1IdpPut = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('put', '/profile/v1/idp', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/idp [PATCH]
 * @param {IDPPatch} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<IDPOut, unknown, IDPPatch>}
 */
export const patchIdpV1IdpPatch = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('patch', '/profile/v1/idp', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/idp/events [POST]
 * @param {IDPEvent} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<IDPOut, unknown, IDPEvent>}
 */
export const applyEventV1IdpEventsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/profile/v1/idp/events', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/idp/benchmarks [GET]
 * @returns {import('@tanstack/react-query').QueryResult<IDPBenchmarkRow[]>}
 */
export const benchmarksV1IdpBenchmarksGet = (options) => {
  const queryKey = ['benchmarks_v1_idp_benchmarks_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/idp/benchmarks'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths [GET]
 * @returns {import('@tanstack/react-query').QueryResult<app__schemas__LearningPathOut__2[]>}
 */
export const listPathsV1LearningPathsGet = (options) => {
  const queryKey = ['list_paths_v1_learning_paths_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/learning-paths'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths [POST]
 * @param {LearningPathCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<app__schemas__LearningPathOut__2, unknown, LearningPathCreate>}
 */
export const createPathV1LearningPathsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/profile/v1/learning-paths', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/{path_id} [PATCH]
 * @param {LearningPathUpdate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<app__schemas__LearningPathOut__2, unknown, LearningPathUpdate>}
 */
export const updatePathV1LearningPaths_PathId_Patch = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('patch', '/profile/v1/learning-paths/{path_id}', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/{path_id}/skills [GET]
 * @returns {import('@tanstack/react-query').QueryResult<LPSkillOut[]>}
 */
export const listSkillsV1LearningPaths_PathId_SkillsGet = (options) => {
  const queryKey = ['list_skills_v1_learning_paths__path_id__skills_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/learning-paths/{path_id}/skills'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/{path_id}/skills [POST]
 * @param {LPSkillIn} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<LPSkillOut, unknown, LPSkillIn>}
 */
export const addSkillV1LearningPaths_PathId_SkillsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/profile/v1/learning-paths/{path_id}/skills', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/{path_id}/skills [PUT]
 * @param {LPSkillIn[]} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<LPSkillOut[], unknown, LPSkillIn[]>}
 */
export const bulkUpsertSkillsV1LearningPaths_PathId_SkillsPut = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('put', '/profile/v1/learning-paths/{path_id}/skills', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/{path_id}/skills/{skill_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, void>}
 */
export const removeSkillV1LearningPaths_PathId_Skills_SkillId_Delete = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('delete', '/profile/v1/learning-paths/{path_id}/skills/{skill_id}', data),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/{path_id}/skills/{skill_id} [PATCH]
 * @param {LPSkillPatch} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<LPSkillOut, unknown, LPSkillPatch>}
 */
export const patchSkillV1LearningPaths_PathId_Skills_SkillId_Patch = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('patch', '/profile/v1/learning-paths/{path_id}/skills/{skill_id}', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/me/default/snapshot [GET]
 * @returns {import('@tanstack/react-query').QueryResult<LPSnapshotOut>}
 */
export const myDefaultSnapshotV1LearningPathsMeDefaultSnapshotGet = (options) => {
  const queryKey = ['my_default_snapshot_v1_learning_paths_me_default_snapshot_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/learning-paths/me/default/snapshot'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/learning-paths/{path_id}/summary [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const pathSummaryV1LearningPaths_PathId_SummaryGet = (options) => {
  const queryKey = ['path_summary_v1_learning_paths__path_id__summary_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/learning-paths/{path_id}/summary'),
    ...options,
  });
};

/**
 * @description Hook for /profile/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const profileRoot_Get = (options) => {
  const queryKey = ['profile_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const profileHealthCheckV1HealthGet = (options) => {
  const queryKey = ['profile_health_check_v1_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/health'),
    ...options,
  });
};

/**
 * @description Hook for /profile/v1/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const profileHealthzV1HealthzGet = (options) => {
  const queryKey = ['profile_healthz_v1_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/profile/v1/healthz'),
    ...options,
  });
};
